# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: affaad2042d6543d804e10c94df16818aa9fa93a98d757ed21865937248e5d6a9d95432d9c9f34ec2f24648e80cee4ae6a6f274b8a87e792277f8f5a46c0fdcc

test:
  secret_key_base: bb0e3e16b43f4bc1781e388cd435fd69cf044341ed6285a9db6f9be02b5e1251e46794bd1a77a76b942d2b0bf73911b82df02de63f1da3471ec667f9a379650e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
